using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace DataLayer.Models;

/// <summary>
/// The User class represents the "user" table in the database.
/// </summary>
[Table("user")]
public class User
{
    /// <summary>
    /// Id property is the primary key for the User table. It's auto-generated by the database.
    /// </summary>
    [Key]
    [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
    [Column("id")]
    public int Id { get; set; }

    /// <summary>
    /// Username property represents the username of the user in the User table.
    /// </summary>
    [Column("username")]
    public string Username { get; set; }

    /// <summary>
    /// Email property represents the email of the user in the User table.
    /// </summary>
    [Column("email")]
    public string Email { get; set; }

    /// <summary>
    /// Password property represents the password of the user in the User table.
    /// </summary>
    [Column("password")]
    public string Password { get; set; }

    /// <summary>
    /// RegistrationDate property represents the date of registration of the user in the User table.
    /// </summary>
    [Column("registration_date")]
    public DateTime RegistrationDate { get; set; }

    /// <summary>
    /// IsAdmin property indicates whether the user is an admin or not in the User table.
    /// </summary>
    [Column("isadmin")]
    public bool IsAdmin { get; set; }
}
